print(" ==============")
print("| Best Frined |")
print("|   Maker!!!  |")
print(" ==============")
print("")
print("Hi. I'm the computer")
name = input("What is your name?")
print(f"hello {name}")
color = input(f"Hi isiah! What's you favorite color?")
print(f"NO WAY! My favorite color is also {color}")
movie = input(f"What is your favorite movie?")
print(f"No way {name} my favorite movie is also {movie}")
game = input(f"What is your favorite game?")
print(f"Get out if here! My favorite game is {game}")
print("We like the same things! We should be best friends!!!")